services:
  sportclub-api:
    build: . 

    ports:
      - "8000:8000"

    restart: always

    container_name: sportclub-api

    environment:
      - LOG_LEVEL=INFO
      
    volumes:
      - ./:/app 
      
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
